services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_NAME: postgres
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      CAPYBARA_SERVER_HOST: app
      CAPYBARA_APP_HOST: http://app
  selenium_chrome:
    image: seleniarm/standalone-chromium:4.17.0
    ports:
      - '4444:4444'
volumes:
  db:
